### PR TITLE
Do not use the pip's internal api as it isn't working anymore

### PR DESCRIPTION
**Pull request by bellini666**
This is an issue that is happening when installing this package in a docker build:

```
  Downloading python-akismet-0.4.1.tar.gz (9.8 kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/local/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-3jz4gexg/python-akismet/setup.py'"'"'; __file__='"'"'/tmp/pip-install-3jz4gexg/python-akismet/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-3_i07rpq
         cwd: /tmp/pip-install-3jz4gexg/python-akismet/
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-3jz4gexg/python-akismet/setup.py", line 186, in <module>
        install_requires = [str(ir.req) for ir in requirements]
      File "/tmp/pip-install-3jz4gexg/python-akismet/setup.py", line 186, in <listcomp>
        install_requires = [str(ir.req) for ir in requirements]
    AttributeError: 'ParsedRequirement' object has no attribute 'req'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

### CODE REVIEW

**Comment by Nekmo** [comment]
What is your Pip and Python version?

**Comment by Nekmo** [comment]
Confirmed in Python 3.8 & Pip 20.0.2:

```
(tmp-53f2b4434fa2079) [nekmo@homura ~/.virtualenvs/tmp-53f2b4434fa2079]$ pip install python-akismet
Collecting python-akismet
  Using cached python-akismet-0.4.1.tar.gz (9.8 kB)
    ERROR: Command errored out with exit status 1:
     command: /home/nekmo/.virtualenvs/tmp-53f2b4434fa2079/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-b4w8yrvs/python-akismet/setup.py'"'"'; __file__='"'"'/tmp/pip-install-b4w8yrvs/python-akismet/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-srk_a42x
         cwd: /tmp/pip-install-b4w8yrvs/python-akismet/
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-b4w8yrvs/python-akismet/setup.py", line 186, in <module>
        install_requires = [str(ir.req) for ir in requirements]
      File "/tmp/pip-install-b4w8yrvs/python-akismet/setup.py", line 186, in <listcomp>
        install_requires = [str(ir.req) for ir in requirements]
    AttributeError: 'ParsedRequirement' object has no attribute 'req'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by bellini666** [comment]
@Nekmo I'm using python 3.8 and pip 20.0.2.

Locally I don't have the issue. It happens only when I try to install the package inside docker. You can try by using a docker from `python:3.8` tag and the problem should happen

This is a problem that just started to happen. You can see for example in this issue (https://github.com/ansible/awx/issues/6870) that they had the same problem 3 days ago.

**Comment by Nekmo** [comment]
I would like to keep the requirements file to maintain the dependencies, I am looking for alternatives...

**Comment by bellini666** [comment]
@Nekmo I thought about looking for something like that, but then I saw that there's only one dependency and this is a project that didn't change for months, so IMO it seems like an unnecessary optimization.

You could always do something like this: https://github.com/stoq/stoq/blob/master/setup.py#L166 , but again, seems like an over engineering for this project.

**Comment by Nekmo** [comment]
Thanks!

**Pull request merged**
